POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkYW0iLCJpZCI6IjY0MzZmZTdiZmRhMzhjYmFiOTE4MzliZiIsImlhdCI6MTY4MTMyNTcxOH0.YQCo-4crIVJIgFfz-DxvSsO_vjK6pYfQOtBbEMUuu6E

{
    "content": "Single page app does not exist",
    "important": true
}